// Prose for the Lab 7 report. Kept separate from diagram data so the narrative
// can be edited without touching the BPMN model.

const intro = `This report applies <strong>BPMN 2.0</strong> (Business Process Model and Notation, the OMG/ISO&nbsp;19510 standard) to the <strong>life cycle</strong> of the <em>ModellingClub</em> system that was specified and built across the previous laboratories. Earlier labs delivered the running artefact: a Spring&nbsp;Boot + Angular community platform for RC / drone / scale-model builders (Lab&nbsp;4), an RDF4J ontology of its domain (Lab&nbsp;5) and a semantic (RDFa / JSON-LD) publication of its data (Lab&nbsp;6). Those labs modelled what the software <em>does</em>. Lab&nbsp;7 instead models the <em>processes that surround the software over its lifetime</em> — the activities a real deployment depends on but which are not, and need not be, encoded in the source: scheduled maintenance and backups, releases and deployments, a database migration, data retention and erasure, security incident response, dependency upgrades, the business contracts under which the system is hosted, and its eventual decommissioning.`;

const why = `Crucially, these processes are governed by formal rules, good practice and external commitments rather than by code. Their participants reach well beyond "administrators and users": the eight models below introduce a DevOps engineer, a Release&nbsp;Manager, a DBA, a Data&nbsp;Protection Officer, a Security on-call engineer, an Operations Committee, an external Cloud&nbsp;Provider, a supervisory authority (GDPR regulator) and offsite storage. Modelling them in BPMN makes the responsibilities, hand-offs, decision points and failure/rollback paths explicit and auditable — exactly what a small platform needs before it can be operated responsibly in production.`;

const systemContext = `<strong>ModellingClub</strong> is a full-stack web application. The backend is Spring&nbsp;Boot&nbsp;3.5 on Java&nbsp;21 (OpenAPI-first REST, JWT authentication, Spring&nbsp;AOP audit logging, JPA persistence); the frontend is Angular&nbsp;21 with server-side rendering on a Node server. In development the database is an <strong>H2</strong> file (<code>modellingclubdb.mv.db</code>) and member-uploaded media (images, PDFs, STL files) live on disk under <code>uploads/</code>; the production roadmap migrates the database to <strong>PostgreSQL</strong> using Flyway and serves the stack behind nginx. The domain entities — Builds, Test&nbsp;runs, Marketplace listings, Messages, Telemetry, Reputation and Users (roles <em>member</em> / <em>admin</em>) — and real product features such as the account <em>data&nbsp;export</em> (JSON&nbsp;→&nbsp;ZIP), <em>account deletion</em>, the admin <em>moderation queue</em> and the 24-hour <em>JWT</em> tokens are the concrete anchors for the life-cycle processes that follow. Where a model references a command, a port or a configuration flag, it is the one actually used by the system (e.g. <code>mvn&nbsp;package</code>, <code>ddl-auto=validate</code>, the actuator health endpoint, the <code>/auth/login</code> route).`;

const primer = `Each diagram is a BPMN <strong>collaboration</strong>: rectangular <em>pools</em> are the independent participants and the horizontal <em>lanes</em> inside a pool are roles/responsibilities. A solid arrow is a <strong>sequence flow</strong> (control flow inside one pool); a dashed arrow is a <strong>message flow</strong> (a message crossing the boundary between two pools). <em>Black-box</em> pools (drawn empty, marked&nbsp;▪) are external participants whose internals are out of scope. Circles are <strong>events</strong> (thin border = start, thick = end, double = intermediate/boundary) and the icon inside gives the trigger (clock = timer, envelope = message, triangle = signal, bolt = error, ring = terminate). Diamonds are <strong>gateways</strong>: <code>×</code> exclusive (choose one path on a condition), <code>+</code> parallel (all paths concurrently), and the pentagon is event-based. Rounded rectangles are <strong>tasks</strong>, with a small marker for the task type (person = user, gear = service, envelope = send/receive, hand = manual, page = script, table = business-rule). The legend below summarises the full palette used in this report.`;

const closing = `<strong>Syntactic and logical correctness.</strong> Every model was checked against the BPMN execution semantics: each path reaches an end event; every gateway either re-merges its branches or each branch terminates; outgoing flows of exclusive and event-based gateways carry mutually-exclusive conditions; parallel splits are matched by parallel joins; message flows only ever cross a pool boundary and never connect two nodes of the same pool. In addition to the rendered diagrams in this report, each process is delivered as an editable <code>.bpmn</code> file (BPMN&nbsp;2.0 XML with diagram interchange) that opens directly in the Camunda&nbsp;Modeler; all eight files were verified to import without warnings using the <code>bpmn-moddle</code> reference parser that underpins Camunda / bpmn.io.`;

const narratives = {
  'p1-backup': `Operational continuity for ModellingClub rests on a dependable backup. Every night at 02:00 a cron <em>timer start event</em> launches the job: a script task stamps the run, then a <em>parallel gateway</em> fans out two concurrent service tasks — one dumps the database (a file copy of <code>modellingclubdb.mv.db</code> in development, <code>pg_dump</code> under the planned PostgreSQL production profile), the other <code>tar&nbsp;+&nbsp;gzip</code>s the whole <code>uploads/</code> media directory. The streams re-join, and a script task computes SHA-256 checksums against a manifest — the integrity gate. An <em>exclusive gateway</em> branches on the result: valid checksums trigger a send task that ships the bundle to an external <em>black-box</em> Offsite Backup Storage pool (e.g. AWS&nbsp;S3) over a message flow, and the administrator is notified of success. A <em>boundary error event</em> on the transfer task catches network/authentication failures; that path, like a checksum mismatch, converges on an alert to the administrator, who is then walked through a manual restore from the last known-good bundle. The process closes on either a clean end event or an <em>error end event</em> that records the incident.`,

  'p2-upgrade': `Dependency hygiene is continuous. The process starts when the Monitoring pool delivers a Dependabot / CVE webhook as a <em>message start event</em>. A business-rule task scores the finding (CVSS, transitive dependency tree, Spring&nbsp;Boot / Angular release notes) and an <em>exclusive gateway</em> splits on severity: a critical vulnerability (CVSS&nbsp;≥&nbsp;7.0, e.g. a Spring RCE) takes an expedited track and mobilises on-call DevOps; a routine bump joins the ordinary patch queue. Both converge on a staging deployment that rebuilds the jar and the Angular SSR bundle and runs the integration suite. A staging gateway <em>loops back</em> to a developer fix task on failure, so the patch can be re-pinned and re-tested without ever touching production. Once staging is green, an <em>intermediate timer event</em> holds the flow until the agreed maintenance window (the next available slot for critical, Saturday&nbsp;03:00 for routine). Production is updated with a rolling restart behind nginx; automated smoke tests then hit the actuator health endpoint, reporting back to Monitoring. A final gateway either notifies success or runs a rollback to the previous jar/bundle, signalling the incident and ending on an error end event.`,

  'p3-cicd': `This is the everyday change pipeline. A merge to <code>main</code> arrives as a <em>message start event</em> into the CI&nbsp;Pipeline lane and immediately fans out through a <em>parallel gateway</em>: Maven builds the backend jar while Angular bundles the SSR frontend. The artifacts re-join and a second parallel split runs the test suites concurrently (<code>mvn&nbsp;test</code>; <code>npm&nbsp;test</code>&nbsp;+&nbsp;<code>tsc&nbsp;--noEmit</code>). A test gateway <em>loops failures back</em> to the developer to fix and re-run. On success the artifacts are published and auto-deployed to a <em>Staging</em> black-box pool, where QA runs a manual smoke test; failures rejoin the fix loop. A passing build reaches a <em>manual approval gate</em> held by the Release&nbsp;Manager, who may reject (ending the run) or approve. Approval triggers a <strong>blue-green</strong> deployment: Ops deploys to the idle green slot of the <em>Production</em> pool while blue keeps serving, runs an actuator health check, then switches the nginx upstream and runs a post-deploy smoke test. Any failure in the health check or post-deploy smoke takes the <em>rollback</em> path — nginx reverts to the still-running blue slot, guaranteeing zero downtime — while success ends the process cleanly. The five lanes (Developer, CI&nbsp;Pipeline, QA, Release&nbsp;Manager, Ops) make every hand-off explicit.`,

  'p4-migration': `A planned, reversible cut-over from H2 to PostgreSQL — the migration described in the project runbook. After the DBA and Release&nbsp;Manager approve (a <em>none start event</em>), the developer adds the Postgres driver and Flyway, and the DBA generates <code>V1__baseline.sql</code> from the H2 schema, hand-adapting dialect differences (UUID and <code>TIMESTAMPTZ</code> types). Testcontainers integration tests validate the mappings against a real Postgres image; failures <em>loop back</em> to a SQL-fix task. Once green, the Release&nbsp;Manager schedules a maintenance window and sends a notice to the external <em>Users</em> pool; an <em>intermediate timer event</em> holds the flow until the window opens. Ops then puts the live system into maintenance/read-only mode (a message to the <em>Production</em> pool), the DBA dumps H2 in FK-safe order, provisions Postgres, loads the dump and runs <code>flyway&nbsp;migrate</code>, and the datasource is switched with <code>ddl-auto=validate</code>. Verification queries (row counts, FK integrity) and a QA smoke test each gate the outcome: either maintenance mode is lifted and the Release&nbsp;Manager signs off and archives the runbook, or — because the H2 file is left untouched throughout — the datasource is reverted to H2 and the team is notified. Two end states make the rollback path first-class.`,

  'p5-data-gdpr': `One model carries two intertwined data-governance duties, with two start events. A nightly <em>timer start</em> runs the retention job: it identifies records past their retention window (old test runs, messages, sold listings), archives the batch to an external <em>Archive&nbsp;Store</em> pool, purges them from the live database and writes an audit entry. Independently, a <em>message start</em> fires when a member submits a request from their account page. Identity is verified against the JWT session and the username challenge already enforced in the UI, and an <em>exclusive gateway</em> branches on request type. An <em>export</em> compiles the member's profile, builds and comments into the JSON&nbsp;→&nbsp;ZIP download already offered by the product, delivered over a message flow. A <em>deletion</em> (right to erasure) goes to the DPO lane: if a legal hold applies (an open dispute or financial-record obligation) the request is parked and the member notified; otherwise marketplace transaction records are anonymised in place for compliance, the remaining personal data is hard-deleted, and a confirmation is sent. A <em>non-interrupting boundary timer</em> on identity verification enforces the GDPR Article&nbsp;12 thirty-day deadline, escalating to notification if the handler stalls. Message end events mark the delivered export and completed erasure.`,

  'p6-incident': `When the SIEM crosses a threshold it raises a <em>signal start event</em> — for example a brute-force spike on the un-rate-limited <code>/auth/login</code> route, an anomaly in the Spring AOP audit log, or an alert that the HS256 JWT secret has leaked. An enrichment task correlates logs, IP reputation and affected accounts before a three-way <em>exclusive gateway</em> triages severity. <em>Low</em> events are logged and thresholds tightened; <em>high</em> events get scoped mitigations and a team notification; <em>critical</em> events enter a <em>parallel</em> containment block that rotates the JWT secret (which, by design, invalidates every 24-hour token and forces a global re-login), blocks the offending IPs, and optionally engages maintenance mode. A <em>non-interrupting boundary timer</em> escalates a stalled high-severity case to critical after one hour. After containment re-joins, a breach gateway decides whether personal data was exposed; if so the DPO is engaged, affected users are notified, and a <em>72-hour intermediate timer</em> enforces the GDPR Article&nbsp;33 obligation to notify the supervisory authority. The process always ends with eradication, recovery verification and a mandatory post-incident review whose gateway can spawn a concrete hardening task — for instance, finally adding rate limiting to <code>/auth/login</code> — so incidents drive durable improvement.`,

  'p7-onboarding': `A three-party collaboration covering both the human and the organisational side of growth. A <em>Prospective Member</em> submits the registration form, which crosses as a message to the Membership&nbsp;Admin lane; the admin creates a pending account and sends a JWT-encoded verification email. A <em>boundary timer</em> resends once if the link is not clicked within 24&nbsp;hours; an <em>exclusive gateway</em> then either activates the account (after the admin moderates the member's first build, mirroring the real admin queue) or lets the registration expire. In parallel — and this is the part not visible in the source code — the <em>Operations&nbsp;Committee</em> negotiates the infrastructure the platform runs on: it sends a hosting quote request to an external <em>Cloud&nbsp;Provider</em> pool, receives a quote and SLA, and an exclusive gateway accepts or rejects on cost and uptime terms (e.g. reject if uptime&nbsp;&lt;&nbsp;99.5%). On acceptance the signed contract is transmitted, the provider provisions the environment and signals readiness, and the committee configures DNS and goes live. The intermediate message catch events and the cross-pool message flows (registration, verification, quote, signed contract, environment-ready) make this a textbook BPMN collaboration with genuinely independent, communicating participants.`,

  'p8-eol': `Software has an end. When the Operations&nbsp;Committee passes an EOL resolution (a <em>none start event</em>), it announces the shutdown to the external <em>Members</em> pool and waits out a 30-day statutory notice period on an <em>intermediate timer</em>. It then opens a final data-export window — reusing the product's own JSON&nbsp;→&nbsp;ZIP export so members can retrieve their builds and media — held open by a second timer while the Membership&nbsp;Admin lane supports requests. In parallel, the resolution signals the Legal&nbsp;&amp;&nbsp;DPO lane, which reviews retention obligations and moves records that must survive (financial / contest data, kept per law for ~7 years) to a long-term legal archive. After the window closes and the platform is locked, an <em>exclusive gateway</em> decides whether any data must be migrated or handed over before a full archive is written to cold storage; all keys, tokens and TLS credentials are revoked; and a formal termination notice crosses to the <em>Cloud&nbsp;Provider</em>, which tears down the VPS, storage and DNS and confirms. A final public notice is published and the process closes on a <em>terminate end event</em>, cancelling any remaining tokens to mark the system fully decommissioned.`,
};

const groups = [
  { title: 'A. Maintenance & operations', ids: ['p1-backup', 'p2-upgrade'] },
  { title: 'B. Deployment & migration', ids: ['p3-cicd', 'p4-migration'] },
  { title: 'C. Data governance & security', ids: ['p5-data-gdpr', 'p6-incident'] },
  { title: 'D. Business life cycle', ids: ['p7-onboarding', 'p8-eol'] },
];

const references = [
  ['OMG', 'Business Process Model and Notation (BPMN) Version 2.0.2', 'https://www.omg.org/spec/BPMN/'],
  ['ISO/IEC', '19510:2013 — Information technology — OMG BPMN', 'https://www.iso.org/standard/62652.html'],
  ['Camunda', 'BPMN 2.0 Modeling Reference', 'https://camunda.com/bpmn/reference/'],
  ['Camunda', 'BPMN 2.0 Examples', 'https://camunda.com/bpmn/examples/'],
  ['Camunda', 'Modeler (desktop BPMN editor)', 'https://camunda.com/products/modeler/'],
  ['BPMB', 'BPMN 2.0 Poster / cheat-sheet', 'http://www.bpmb.de/images/BPMN2_0_Poster_EN.pdf'],
  ['EU', 'GDPR — Regulation (EU) 2016/679, Articles 12, 17, 33', 'https://gdpr-info.eu/'],
];

module.exports = { intro, why, systemContext, primer, closing, narratives, groups, references };
