// ModellingClub — Lab 7 BPMN process specifications (normalized, implementable).
// Each spec is rendered to (a) a self-contained SVG diagram for the report and
// (b) a Camunda-compatible BPMN 2.0 XML file with diagram interchange (DI).
//
// Node kinds:
//   startEvent / intermediateCatch / intermediateThrow / endEvent / boundaryEvent
//   task            (with subtype marker: user|service|manual|send|receive|script|business)
//   exclusiveGateway | parallelGateway | eventBasedGateway
//   dataObject | dataStore (declared in `data`) | textAnnotation (declared in `annotations`)
// Markers on events: none|timer|message|signal|error|terminate
// Pools: { id, name, lanes:[...], blackbox?:true }.  Single-lane pool => lanes:[]; nodes set lane:null.
// Message flows connect nodes OR pool ids and must cross pool boundaries.

const P1 = {
  id: 'p1-backup', num: 1,
  title: 'Scheduled Backup & Verification',
  goal: 'Nightly automated backup of the ModellingClub database and the uploads/ media directory, with integrity verification, offsite transfer and a restore-from-last-good path on failure.',
  trigger: 'Timer start event firing at 02:00 every day (cron scheduler).',
  constructs: 'Timer start event, parallel gateway (split & join), exclusive (data-based) gateway, service/script/send/manual tasks, boundary error event, error end event, message flow to an external black-box pool, data object & data store.',
  pools: [
    { id: 'POOL_OPS', name: 'ModellingClub Operations', lanes: ['Scheduler', 'System', 'Administrator'] },
    { id: 'POOL_STORE', name: 'Offsite Backup Storage (AWS S3)', lanes: [], blackbox: true },
  ],
  nodes: [
    { id: 'EVT_START', kind: 'startEvent', marker: 'timer', pool: 'POOL_OPS', lane: 'Scheduler', label: '02:00 nightly backup timer' },
    { id: 'TASK_INIT', kind: 'task', sub: 'script', pool: 'POOL_OPS', lane: 'System', label: 'Initialise backup job & set timestamp' },
    { id: 'GW_SPLIT', kind: 'parallelGateway', pool: 'POOL_OPS', lane: 'System', label: 'Begin parallel backup' },
    { id: 'TASK_DB_BACKUP', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'System', label: 'Dump DB (H2 file copy / pg_dump)' },
    { id: 'TASK_MEDIA_BACK', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'System', label: 'Archive uploads/ directory (tar + gzip)' },
    { id: 'GW_JOIN', kind: 'parallelGateway', pool: 'POOL_OPS', lane: 'System', label: 'Await both streams' },
    { id: 'TASK_VERIFY', kind: 'task', sub: 'script', pool: 'POOL_OPS', lane: 'System', label: 'Verify archive checksums (SHA-256)' },
    { id: 'GW_VERIFY_OK', kind: 'exclusiveGateway', pool: 'POOL_OPS', lane: 'System', label: 'Verification passed?' },
    { id: 'TASK_SEND_OFF', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'System', label: 'Transfer archives to offsite storage' },
    { id: 'BND_ERR_XFER', kind: 'boundaryEvent', marker: 'error', attachedTo: 'TASK_SEND_OFF', pool: 'POOL_OPS', lane: 'System', label: 'Transfer error' },
    { id: 'TASK_NOTIFY_OK', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Administrator', label: 'Notify admin: backup successful' },
    { id: 'TASK_ALERT_FAIL', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Administrator', label: 'Alert admin: backup / verify failed' },
    { id: 'TASK_RESTORE', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Administrator', label: 'Restore from last known-good backup' },
    { id: 'EVT_END_OK', kind: 'endEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Administrator', label: 'Backup cycle complete' },
    { id: 'EVT_END_FAIL', kind: 'endEvent', marker: 'error', pool: 'POOL_OPS', lane: 'Administrator', label: 'Backup failed — incident logged' },
  ],
  flows: [
    ['EVT_START', 'TASK_INIT'], ['TASK_INIT', 'GW_SPLIT'],
    ['GW_SPLIT', 'TASK_DB_BACKUP'], ['GW_SPLIT', 'TASK_MEDIA_BACK'],
    ['TASK_DB_BACKUP', 'GW_JOIN'], ['TASK_MEDIA_BACK', 'GW_JOIN'],
    ['GW_JOIN', 'TASK_VERIFY'], ['TASK_VERIFY', 'GW_VERIFY_OK'],
    ['GW_VERIFY_OK', 'TASK_SEND_OFF', 'checksums valid'],
    ['GW_VERIFY_OK', 'TASK_ALERT_FAIL', 'checksum mismatch'],
    ['TASK_SEND_OFF', 'TASK_NOTIFY_OK'],
    ['BND_ERR_XFER', 'TASK_ALERT_FAIL'],
    ['TASK_NOTIFY_OK', 'EVT_END_OK'],
    ['TASK_ALERT_FAIL', 'TASK_RESTORE'], ['TASK_RESTORE', 'EVT_END_FAIL'],
  ],
  messages: [
    { from: 'TASK_SEND_OFF', to: 'POOL_STORE', label: 'Archive bundle (DB + media)' },
  ],
  data: [
    { id: 'DS_LOG', kind: 'dataStore', label: 'Backup run log', attached: 'TASK_VERIFY' },
    { id: 'DO_LASTGOOD', kind: 'dataObject', label: 'Last-good backup ref', attached: 'TASK_RESTORE' },
  ],
  annotations: [
    { attached: 'TASK_VERIFY', text: 'sha256sum of both archives vs manifest' },
    { attached: 'TASK_RESTORE', text: 'Admin picks last-good bundle, runs restore script' },
  ],
};

const P2 = {
  id: 'p2-upgrade', num: 2,
  title: 'Software Upgrade / Dependency Patch',
  goal: 'Manage a security / dependency update (e.g. a Dependabot PR for a Spring Boot or Angular CVE) from triage through staging validation, scheduled production deployment and rollback, so no unvetted code reaches production.',
  trigger: 'Message start event: a Dependabot PR / CVE webhook arrives from the monitoring system.',
  constructs: 'Message start event, business-rule task, exclusive gateways (severity branch + two outcome branches), intermediate catch timer (maintenance window), loop-back sequence flow, send tasks, message flows to/from an external pool, data objects, error end event.',
  pools: [
    { id: 'POOL_ENG', name: 'ModellingClub Engineering', lanes: ['Developer', 'DevOps', 'System'] },
    { id: 'POOL_MON', name: 'Monitoring System', lanes: [], blackbox: true },
  ],
  nodes: [
    { id: 'EVT_START_PR', kind: 'startEvent', marker: 'message', pool: 'POOL_ENG', lane: 'Developer', label: 'Dependabot PR / CVE alert received' },
    { id: 'TASK_ASSESS', kind: 'task', sub: 'business', pool: 'POOL_ENG', lane: 'Developer', label: 'Assess severity & impact (CVSS, deps tree)' },
    { id: 'GW_SEVERITY', kind: 'exclusiveGateway', pool: 'POOL_ENG', lane: 'Developer', label: 'Severity level?' },
    { id: 'TASK_EXPEDITE', kind: 'task', sub: 'user', pool: 'POOL_ENG', lane: 'Developer', label: 'Trigger expedited patch track' },
    { id: 'TASK_SCHEDULE', kind: 'task', sub: 'user', pool: 'POOL_ENG', lane: 'Developer', label: 'Add to routine patch queue' },
    { id: 'TASK_STAGE_DEP', kind: 'task', sub: 'service', pool: 'POOL_ENG', lane: 'DevOps', label: 'Deploy patch to staging (CI)' },
    { id: 'TASK_STAGE_TEST', kind: 'task', sub: 'service', pool: 'POOL_ENG', lane: 'DevOps', label: 'Run smoke & integration tests' },
    { id: 'GW_STAGE_OK', kind: 'exclusiveGateway', pool: 'POOL_ENG', lane: 'DevOps', label: 'Staging tests passed?' },
    { id: 'TASK_FIX_PATCH', kind: 'task', sub: 'user', pool: 'POOL_ENG', lane: 'Developer', label: 'Fix / pin version' },
    { id: 'EVT_MAINT_WIN', kind: 'intermediateCatch', marker: 'timer', pool: 'POOL_ENG', lane: 'DevOps', label: 'Await maintenance window' },
    { id: 'TASK_PROD_DEP', kind: 'task', sub: 'service', pool: 'POOL_ENG', lane: 'DevOps', label: 'Deploy to production (rolling restart)' },
    { id: 'TASK_SMOKE_PROD', kind: 'task', sub: 'service', pool: 'POOL_ENG', lane: 'System', label: 'Production smoke tests & actuator health' },
    { id: 'GW_PROD_OK', kind: 'exclusiveGateway', pool: 'POOL_ENG', lane: 'DevOps', label: 'Smoke tests passed?' },
    { id: 'TASK_ROLLBACK', kind: 'task', sub: 'service', pool: 'POOL_ENG', lane: 'DevOps', label: 'Rollback: redeploy previous jar / bundle' },
    { id: 'TASK_NOTIFY_DEV', kind: 'task', sub: 'send', pool: 'POOL_ENG', lane: 'Developer', label: 'Notify team: upgrade complete' },
    { id: 'TASK_ALERT_ROLL', kind: 'task', sub: 'send', pool: 'POOL_ENG', lane: 'Developer', label: 'Alert team: rollback executed' },
    { id: 'EVT_END_OK', kind: 'endEvent', marker: 'none', pool: 'POOL_ENG', lane: 'Developer', label: 'Upgrade applied' },
    { id: 'EVT_END_ROLL', kind: 'endEvent', marker: 'error', pool: 'POOL_ENG', lane: 'Developer', label: 'Rollback complete — patch deferred' },
  ],
  flows: [
    ['EVT_START_PR', 'TASK_ASSESS'], ['TASK_ASSESS', 'GW_SEVERITY'],
    ['GW_SEVERITY', 'TASK_EXPEDITE', 'critical (CVSS ≥ 7.0)'],
    ['GW_SEVERITY', 'TASK_SCHEDULE', 'routine (CVSS < 7.0)'],
    ['TASK_EXPEDITE', 'TASK_STAGE_DEP'], ['TASK_SCHEDULE', 'TASK_STAGE_DEP'],
    ['TASK_STAGE_DEP', 'TASK_STAGE_TEST'], ['TASK_STAGE_TEST', 'GW_STAGE_OK'],
    ['GW_STAGE_OK', 'EVT_MAINT_WIN', 'passed'],
    ['GW_STAGE_OK', 'TASK_FIX_PATCH', 'failed'],
    ['TASK_FIX_PATCH', 'TASK_STAGE_DEP'],
    ['EVT_MAINT_WIN', 'TASK_PROD_DEP'], ['TASK_PROD_DEP', 'TASK_SMOKE_PROD'],
    ['TASK_SMOKE_PROD', 'GW_PROD_OK'],
    ['GW_PROD_OK', 'TASK_NOTIFY_DEV', 'passed'],
    ['GW_PROD_OK', 'TASK_ROLLBACK', 'failed'],
    ['TASK_NOTIFY_DEV', 'EVT_END_OK'],
    ['TASK_ROLLBACK', 'TASK_ALERT_ROLL'], ['TASK_ALERT_ROLL', 'EVT_END_ROLL'],
  ],
  messages: [
    { from: 'POOL_MON', to: 'EVT_START_PR', label: 'Dependabot / CVE webhook' },
    { from: 'TASK_SMOKE_PROD', to: 'POOL_MON', label: 'Health-check results' },
    { from: 'TASK_ALERT_ROLL', to: 'POOL_MON', label: 'Rollback incident signal' },
  ],
  data: [
    { id: 'DO_CVE', kind: 'dataObject', label: 'CVE / Dependabot report', attached: 'TASK_ASSESS' },
    { id: 'DO_PREV', kind: 'dataObject', label: 'Previous build ref', attached: 'TASK_ROLLBACK' },
  ],
  annotations: [
    { attached: 'EVT_MAINT_WIN', text: 'Critical: next available slot; routine: Sat 03:00' },
    { attached: 'TASK_FIX_PATCH', text: 'Loop back: pin version / workaround, re-enter staging' },
  ],
};

const P3 = {
  id: 'p3-cicd', num: 3,
  title: 'Release & Blue-Green Deployment (CI/CD)',
  goal: 'Automate build, test, staging deploy and blue-green production deployment from a merge to main, with automatic rollback to the previous (blue) release if health checks or smoke tests fail.',
  trigger: 'Message start event: a push / merge to the main branch reaches the CI pipeline.',
  constructs: 'Message start event, parallel gateways (build & test split/join), exclusive gateways with loop-back, manual & user approval tasks, service & send tasks, message flows to external environment pools, data object & data store, multiple end events, rollback pattern.',
  pools: [
    { id: 'POOL_CICD', name: 'ModellingClub CI/CD', lanes: ['Developer', 'CI Pipeline', 'QA / Tester', 'Release Manager', 'Ops / DevOps'] },
    { id: 'POOL_STG', name: 'Staging Environment', lanes: [], blackbox: true },
    { id: 'POOL_PRD', name: 'Production Environment', lanes: [], blackbox: true },
  ],
  nodes: [
    { id: 'MSG_START', kind: 'startEvent', marker: 'message', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'Push to main received' },
    { id: 'PAR_BUILD_SPLIT', kind: 'parallelGateway', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'Split: build' },
    { id: 'BUILD_BACKEND', kind: 'task', sub: 'service', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'mvn package (build jar)' },
    { id: 'BUILD_FRONTEND', kind: 'task', sub: 'service', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'ng build (SSR bundle)' },
    { id: 'PAR_BUILD_JOIN', kind: 'parallelGateway', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'Join: artifacts ready' },
    { id: 'PAR_TEST_SPLIT', kind: 'parallelGateway', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'Split: tests' },
    { id: 'TEST_BACKEND', kind: 'task', sub: 'service', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'mvn test (JUnit / Spring)' },
    { id: 'TEST_FRONTEND', kind: 'task', sub: 'service', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'npm test + tsc --noEmit' },
    { id: 'PAR_TEST_JOIN', kind: 'parallelGateway', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'Join: tests done' },
    { id: 'GW_TESTS_PASS', kind: 'exclusiveGateway', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'All tests passed?' },
    { id: 'FIX_NOTIFY', kind: 'task', sub: 'send', pool: 'POOL_CICD', lane: 'Developer', label: 'Notify developer: failure' },
    { id: 'FIX_CODE', kind: 'task', sub: 'user', pool: 'POOL_CICD', lane: 'Developer', label: 'Fix failing tests / code' },
    { id: 'PUBLISH_ARTIFACTS', kind: 'task', sub: 'service', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'Publish jar + bundle to registry' },
    { id: 'DEPLOY_STAGING', kind: 'task', sub: 'service', pool: 'POOL_CICD', lane: 'CI Pipeline', label: 'Deploy to staging' },
    { id: 'STAGING_SMOKE', kind: 'task', sub: 'manual', pool: 'POOL_CICD', lane: 'QA / Tester', label: 'Run staging smoke tests' },
    { id: 'GW_STAGING_OK', kind: 'exclusiveGateway', pool: 'POOL_CICD', lane: 'QA / Tester', label: 'Staging smoke passed?' },
    { id: 'APPROVAL_GATE', kind: 'task', sub: 'user', pool: 'POOL_CICD', lane: 'Release Manager', label: 'Review notes; approve / reject' },
    { id: 'GW_APPROVED', kind: 'exclusiveGateway', pool: 'POOL_CICD', lane: 'Release Manager', label: 'Release approved?' },
    { id: 'REJECT_NOTIFY', kind: 'task', sub: 'send', pool: 'POOL_CICD', lane: 'Release Manager', label: 'Notify team: rejected' },
    { id: 'END_REJECTED', kind: 'endEvent', marker: 'none', pool: 'POOL_CICD', lane: 'Release Manager', label: 'Release rejected' },
    { id: 'DEPLOY_GREEN', kind: 'task', sub: 'service', pool: 'POOL_CICD', lane: 'Ops / DevOps', label: 'Deploy to green slot (idle)' },
    { id: 'HEALTH_CHECK', kind: 'task', sub: 'service', pool: 'POOL_CICD', lane: 'Ops / DevOps', label: 'Actuator /health on green' },
    { id: 'GW_HEALTH', kind: 'exclusiveGateway', pool: 'POOL_CICD', lane: 'Ops / DevOps', label: 'Green healthy?' },
    { id: 'SWITCH_TRAFFIC', kind: 'task', sub: 'service', pool: 'POOL_CICD', lane: 'Ops / DevOps', label: 'nginx: switch traffic to green' },
    { id: 'POST_SMOKE', kind: 'task', sub: 'manual', pool: 'POOL_CICD', lane: 'QA / Tester', label: 'Post-deploy production smoke' },
    { id: 'GW_POST_SMOKE', kind: 'exclusiveGateway', pool: 'POOL_CICD', lane: 'QA / Tester', label: 'Post-deploy smoke passed?' },
    { id: 'ROLLBACK', kind: 'task', sub: 'service', pool: 'POOL_CICD', lane: 'Ops / DevOps', label: 'Rollback: nginx back to blue' },
    { id: 'ROLLBACK_NOTIFY', kind: 'task', sub: 'send', pool: 'POOL_CICD', lane: 'Ops / DevOps', label: 'Notify team: rollback executed' },
    { id: 'END_ROLLBACK', kind: 'endEvent', marker: 'none', pool: 'POOL_CICD', lane: 'Ops / DevOps', label: 'Rolled back to blue' },
    { id: 'END_SUCCESS', kind: 'endEvent', marker: 'none', pool: 'POOL_CICD', lane: 'Ops / DevOps', label: 'Deployment successful' },
  ],
  flows: [
    ['MSG_START', 'PAR_BUILD_SPLIT'],
    ['PAR_BUILD_SPLIT', 'BUILD_BACKEND'], ['PAR_BUILD_SPLIT', 'BUILD_FRONTEND'],
    ['BUILD_BACKEND', 'PAR_BUILD_JOIN'], ['BUILD_FRONTEND', 'PAR_BUILD_JOIN'],
    ['PAR_BUILD_JOIN', 'PAR_TEST_SPLIT'],
    ['PAR_TEST_SPLIT', 'TEST_BACKEND'], ['PAR_TEST_SPLIT', 'TEST_FRONTEND'],
    ['TEST_BACKEND', 'PAR_TEST_JOIN'], ['TEST_FRONTEND', 'PAR_TEST_JOIN'],
    ['PAR_TEST_JOIN', 'GW_TESTS_PASS'],
    ['GW_TESTS_PASS', 'PUBLISH_ARTIFACTS', 'all passed'],
    ['GW_TESTS_PASS', 'FIX_NOTIFY', 'one or more failed'],
    ['FIX_NOTIFY', 'FIX_CODE'], ['FIX_CODE', 'PAR_BUILD_SPLIT'],
    ['PUBLISH_ARTIFACTS', 'DEPLOY_STAGING'], ['DEPLOY_STAGING', 'STAGING_SMOKE'],
    ['STAGING_SMOKE', 'GW_STAGING_OK'],
    ['GW_STAGING_OK', 'APPROVAL_GATE', 'passed'],
    ['GW_STAGING_OK', 'FIX_NOTIFY', 'failed'],
    ['APPROVAL_GATE', 'GW_APPROVED'],
    ['GW_APPROVED', 'DEPLOY_GREEN', 'approved'],
    ['GW_APPROVED', 'REJECT_NOTIFY', 'rejected'],
    ['REJECT_NOTIFY', 'END_REJECTED'],
    ['DEPLOY_GREEN', 'HEALTH_CHECK'], ['HEALTH_CHECK', 'GW_HEALTH'],
    ['GW_HEALTH', 'SWITCH_TRAFFIC', 'passed'],
    ['GW_HEALTH', 'ROLLBACK', 'failed'],
    ['SWITCH_TRAFFIC', 'POST_SMOKE'], ['POST_SMOKE', 'GW_POST_SMOKE'],
    ['GW_POST_SMOKE', 'END_SUCCESS', 'passed'],
    ['GW_POST_SMOKE', 'ROLLBACK', 'failed'],
    ['ROLLBACK', 'ROLLBACK_NOTIFY'], ['ROLLBACK_NOTIFY', 'END_ROLLBACK'],
  ],
  messages: [
    { from: 'DEPLOY_STAGING', to: 'POOL_STG', label: 'Deploy artifact to staging' },
    { from: 'POOL_STG', to: 'STAGING_SMOKE', label: 'Staging ready' },
    { from: 'DEPLOY_GREEN', to: 'POOL_PRD', label: 'Deploy green slot' },
    { from: 'SWITCH_TRAFFIC', to: 'POOL_PRD', label: 'Switch nginx upstream to green' },
    { from: 'POOL_PRD', to: 'POST_SMOKE', label: 'Traffic live on green' },
  ],
  data: [
    { id: 'DS_ART', kind: 'dataStore', label: 'Artifact registry', attached: 'PUBLISH_ARTIFACTS' },
    { id: 'DO_NOTES', kind: 'dataObject', label: 'Release notes', attached: 'APPROVAL_GATE' },
  ],
  annotations: [
    { attached: 'DEPLOY_GREEN', text: 'Green slot idle; blue keeps serving traffic' },
    { attached: 'ROLLBACK', text: 'Blue still running — nginx reverts, zero downtime' },
  ],
};

const P4 = {
  id: 'p4-migration', num: 4,
  title: 'H2 → PostgreSQL Database Migration',
  goal: 'Execute a one-time, audited cutover of the H2 file database to PostgreSQL in production, with a Flyway baseline, data migration, verification and a tested rollback to H2.',
  trigger: 'None start event: the DBA and Release Manager jointly approve the migration ticket.',
  constructs: 'None start event, intermediate catch timer (maintenance window), exclusive gateways with loop-back, service/script/manual/user/send tasks, message flows to external Users & Production pools, data objects & data store, two end events, rollback path.',
  pools: [
    { id: 'POOL_MIG', name: 'ModellingClub Migration Team', lanes: ['Developer', 'DBA', 'Release Manager', 'Ops / DevOps', 'QA / Tester'] },
    { id: 'POOL_USERS', name: 'Users', lanes: [], blackbox: true },
    { id: 'POOL_PRD', name: 'Production Environment', lanes: [], blackbox: true },
  ],
  nodes: [
    { id: 'START_APPROVAL', kind: 'startEvent', marker: 'none', pool: 'POOL_MIG', lane: 'Release Manager', label: 'Migration approved' },
    { id: 'PREP_CODE', kind: 'task', sub: 'service', pool: 'POOL_MIG', lane: 'Developer', label: 'Add Postgres driver + Flyway' },
    { id: 'GEN_BASELINE', kind: 'task', sub: 'script', pool: 'POOL_MIG', lane: 'DBA', label: 'Export H2 schema → V1__baseline.sql' },
    { id: 'TEST_CONTAINERS', kind: 'task', sub: 'service', pool: 'POOL_MIG', lane: 'Developer', label: 'Integration test (Testcontainers)' },
    { id: 'GW_TC_PASS', kind: 'exclusiveGateway', pool: 'POOL_MIG', lane: 'Developer', label: 'Tests passed?' },
    { id: 'FIX_SQL', kind: 'task', sub: 'user', pool: 'POOL_MIG', lane: 'Developer', label: 'Fix SQL dialect issues' },
    { id: 'SCHED_WINDOW', kind: 'task', sub: 'user', pool: 'POOL_MIG', lane: 'Release Manager', label: 'Schedule maintenance window' },
    { id: 'NOTIFY_USERS', kind: 'task', sub: 'send', pool: 'POOL_MIG', lane: 'Release Manager', label: 'Send maintenance notice' },
    { id: 'TIMER_WINDOW', kind: 'intermediateCatch', marker: 'timer', pool: 'POOL_MIG', lane: 'Ops / DevOps', label: 'Wait for window start' },
    { id: 'MAINT_MODE', kind: 'task', sub: 'service', pool: 'POOL_MIG', lane: 'Ops / DevOps', label: 'Enable maintenance / read-only mode' },
    { id: 'DUMP_H2', kind: 'task', sub: 'script', pool: 'POOL_MIG', lane: 'DBA', label: 'Dump H2 data (FK-safe order)' },
    { id: 'PROVISION_PG', kind: 'task', sub: 'service', pool: 'POOL_MIG', lane: 'Ops / DevOps', label: 'Provision Postgres; schema + roles' },
    { id: 'LOAD_PG', kind: 'task', sub: 'script', pool: 'POOL_MIG', lane: 'DBA', label: 'Load dump; run Flyway migrate' },
    { id: 'SWITCH_DS', kind: 'task', sub: 'service', pool: 'POOL_MIG', lane: 'Ops / DevOps', label: 'Switch datasource; ddl-auto=validate' },
    { id: 'VERIFY_Q', kind: 'task', sub: 'script', pool: 'POOL_MIG', lane: 'DBA', label: 'Verification queries (counts, FKs)' },
    { id: 'GW_VERIFY', kind: 'exclusiveGateway', pool: 'POOL_MIG', lane: 'DBA', label: 'Verification passed?' },
    { id: 'SMOKE_TEST', kind: 'task', sub: 'manual', pool: 'POOL_MIG', lane: 'QA / Tester', label: 'Post-migration smoke test' },
    { id: 'GW_SMOKE', kind: 'exclusiveGateway', pool: 'POOL_MIG', lane: 'QA / Tester', label: 'Smoke passed?' },
    { id: 'DISABLE_MAINT', kind: 'task', sub: 'service', pool: 'POOL_MIG', lane: 'Ops / DevOps', label: 'Disable maintenance; restore traffic' },
    { id: 'SIGNOFF', kind: 'task', sub: 'user', pool: 'POOL_MIG', lane: 'Release Manager', label: 'Sign off; archive runbook' },
    { id: 'END_SUCCESS', kind: 'endEvent', marker: 'none', pool: 'POOL_MIG', lane: 'Release Manager', label: 'Migration complete' },
    { id: 'ROLLBACK_DS', kind: 'task', sub: 'service', pool: 'POOL_MIG', lane: 'Ops / DevOps', label: 'Revert datasource to H2; restart' },
    { id: 'ROLLBACK_NOTIFY', kind: 'task', sub: 'send', pool: 'POOL_MIG', lane: 'Ops / DevOps', label: 'Notify team: rolled back to H2' },
    { id: 'DISABLE_MAINT_RB', kind: 'task', sub: 'service', pool: 'POOL_MIG', lane: 'Ops / DevOps', label: 'Disable maintenance (rollback)' },
    { id: 'END_ROLLBACK', kind: 'endEvent', marker: 'none', pool: 'POOL_MIG', lane: 'Ops / DevOps', label: 'Rolled back to H2' },
  ],
  flows: [
    ['START_APPROVAL', 'PREP_CODE'], ['PREP_CODE', 'GEN_BASELINE'],
    ['GEN_BASELINE', 'TEST_CONTAINERS'], ['TEST_CONTAINERS', 'GW_TC_PASS'],
    ['GW_TC_PASS', 'SCHED_WINDOW', 'passed'],
    ['GW_TC_PASS', 'FIX_SQL', 'failed'],
    ['FIX_SQL', 'GEN_BASELINE'],
    ['SCHED_WINDOW', 'NOTIFY_USERS'], ['NOTIFY_USERS', 'TIMER_WINDOW'],
    ['TIMER_WINDOW', 'MAINT_MODE'], ['MAINT_MODE', 'DUMP_H2'],
    ['DUMP_H2', 'PROVISION_PG'], ['PROVISION_PG', 'LOAD_PG'],
    ['LOAD_PG', 'SWITCH_DS'], ['SWITCH_DS', 'VERIFY_Q'], ['VERIFY_Q', 'GW_VERIFY'],
    ['GW_VERIFY', 'SMOKE_TEST', 'passed'],
    ['GW_VERIFY', 'ROLLBACK_DS', 'failed'],
    ['SMOKE_TEST', 'GW_SMOKE'],
    ['GW_SMOKE', 'DISABLE_MAINT', 'passed'],
    ['GW_SMOKE', 'ROLLBACK_DS', 'failed'],
    ['DISABLE_MAINT', 'SIGNOFF'], ['SIGNOFF', 'END_SUCCESS'],
    ['ROLLBACK_DS', 'ROLLBACK_NOTIFY'], ['ROLLBACK_NOTIFY', 'DISABLE_MAINT_RB'],
    ['DISABLE_MAINT_RB', 'END_ROLLBACK'],
  ],
  messages: [
    { from: 'NOTIFY_USERS', to: 'POOL_USERS', label: 'Scheduled maintenance notice' },
    { from: 'MAINT_MODE', to: 'POOL_PRD', label: 'Activate maintenance page' },
    { from: 'SWITCH_DS', to: 'POOL_PRD', label: 'Restart with Postgres datasource' },
    { from: 'DISABLE_MAINT', to: 'POOL_PRD', label: 'Deactivate maintenance mode' },
  ],
  data: [
    { id: 'DO_BASELINE', kind: 'dataObject', label: 'V1__baseline.sql', attached: 'GEN_BASELINE' },
    { id: 'DO_DUMP', kind: 'dataObject', label: 'H2 SQL dump', attached: 'DUMP_H2' },
    { id: 'DS_RUNBOOK', kind: 'dataStore', label: 'Migration runbook', attached: 'SIGNOFF' },
  ],
  annotations: [
    { attached: 'GEN_BASELINE', text: 'UUID → uuid; TIMESTAMP → TIMESTAMPTZ' },
    { attached: 'ROLLBACK_DS', text: 'H2 file untouched during migration' },
  ],
};

const P5 = {
  id: 'p5-data-gdpr', num: 5,
  title: 'Data Archiving, Retention & GDPR Erasure',
  goal: 'Periodically archive and purge stale operational data to cold storage, and fulfil member-initiated GDPR requests (data export or right-to-erasure) within statutory deadlines.',
  trigger: 'Two start events: a timer for the retention job and a message for a member GDPR request.',
  constructs: 'Two start events (timer + message), exclusive gateways (request type, legal hold), boundary timer event (30-day deadline), send/service/script/manual tasks, message end events, message flows to Member & Archive Store pools, data store & data object.',
  pools: [
    { id: 'POOL_SYS', name: 'ModellingClub System', lanes: ['Retention Job', 'GDPR Handler', 'DPO Review'] },
    { id: 'POOL_MEMBER', name: 'Member', lanes: [], blackbox: true },
    { id: 'POOL_ARCHIVE', name: 'Archive Store', lanes: [], blackbox: true },
  ],
  nodes: [
    { id: 'START_TIMER', kind: 'startEvent', marker: 'timer', pool: 'POOL_SYS', lane: 'Retention Job', label: 'Nightly retention schedule' },
    { id: 'IDENTIFY_STALE', kind: 'task', sub: 'service', pool: 'POOL_SYS', lane: 'Retention Job', label: 'Identify stale records' },
    { id: 'ARCHIVE_COLD', kind: 'task', sub: 'service', pool: 'POOL_SYS', lane: 'Retention Job', label: 'Archive records to cold storage' },
    { id: 'PURGE_LIVE', kind: 'task', sub: 'service', pool: 'POOL_SYS', lane: 'Retention Job', label: 'Purge stale records from live DB' },
    { id: 'AUDIT_RETENTION', kind: 'task', sub: 'script', pool: 'POOL_SYS', lane: 'Retention Job', label: 'Write retention audit entry' },
    { id: 'END_RETENTION', kind: 'endEvent', marker: 'none', pool: 'POOL_SYS', lane: 'Retention Job', label: 'Retention cycle complete' },
    { id: 'START_GDPR', kind: 'startEvent', marker: 'message', pool: 'POOL_SYS', lane: 'GDPR Handler', label: 'GDPR request received' },
    { id: 'VERIFY_IDENTITY', kind: 'task', sub: 'service', pool: 'POOL_SYS', lane: 'GDPR Handler', label: 'Verify member identity (JWT + username)' },
    { id: 'BND_30D', kind: 'boundaryEvent', marker: 'timer', interrupting: false, attachedTo: 'VERIFY_IDENTITY', pool: 'POOL_SYS', lane: 'GDPR Handler', label: '30-day deadline' },
    { id: 'GW_REQ_TYPE', kind: 'exclusiveGateway', pool: 'POOL_SYS', lane: 'GDPR Handler', label: 'Export or deletion?' },
    { id: 'BUILD_EXPORT', kind: 'task', sub: 'service', pool: 'POOL_SYS', lane: 'GDPR Handler', label: 'Compile profile + builds + comments' },
    { id: 'ZIP_SEND', kind: 'task', sub: 'send', pool: 'POOL_SYS', lane: 'GDPR Handler', label: 'Generate ZIP; notify member' },
    { id: 'END_EXPORT', kind: 'endEvent', marker: 'message', pool: 'POOL_SYS', lane: 'GDPR Handler', label: 'Data export delivered' },
    { id: 'DPO_REVIEW', kind: 'task', sub: 'manual', pool: 'POOL_SYS', lane: 'DPO Review', label: 'DPO reviews deletion request' },
    { id: 'GW_LEGAL_HOLD', kind: 'exclusiveGateway', pool: 'POOL_SYS', lane: 'DPO Review', label: 'Legal hold required?' },
    { id: 'GW_HOLD_HALT', kind: 'exclusiveGateway', pool: 'POOL_SYS', lane: 'DPO Review', label: 'Partial erasure allowed?' },
    { id: 'NOTIFY_HOLD', kind: 'task', sub: 'send', pool: 'POOL_SYS', lane: 'DPO Review', label: 'Notify member of legal hold' },
    { id: 'END_HOLD', kind: 'endEvent', marker: 'none', pool: 'POOL_SYS', lane: 'DPO Review', label: 'Parked pending hold' },
    { id: 'ANONYMISE', kind: 'task', sub: 'script', pool: 'POOL_SYS', lane: 'DPO Review', label: 'Anonymise retained tx records' },
    { id: 'HARD_DELETE', kind: 'task', sub: 'service', pool: 'POOL_SYS', lane: 'GDPR Handler', label: 'Hard-delete member data' },
    { id: 'CONFIRM_ERASURE', kind: 'task', sub: 'send', pool: 'POOL_SYS', lane: 'GDPR Handler', label: 'Send erasure confirmation' },
    { id: 'AUDIT_GDPR', kind: 'task', sub: 'script', pool: 'POOL_SYS', lane: 'GDPR Handler', label: 'Write GDPR audit entry' },
    { id: 'END_ERASURE', kind: 'endEvent', marker: 'message', pool: 'POOL_SYS', lane: 'GDPR Handler', label: 'Erasure complete' },
  ],
  flows: [
    ['START_TIMER', 'IDENTIFY_STALE'], ['IDENTIFY_STALE', 'ARCHIVE_COLD'],
    ['ARCHIVE_COLD', 'PURGE_LIVE'], ['PURGE_LIVE', 'AUDIT_RETENTION'],
    ['AUDIT_RETENTION', 'END_RETENTION'],
    ['START_GDPR', 'VERIFY_IDENTITY'], ['VERIFY_IDENTITY', 'GW_REQ_TYPE'],
    ['GW_REQ_TYPE', 'BUILD_EXPORT', 'export'],
    ['GW_REQ_TYPE', 'DPO_REVIEW', 'deletion'],
    ['BUILD_EXPORT', 'ZIP_SEND'], ['ZIP_SEND', 'END_EXPORT'],
    ['DPO_REVIEW', 'GW_LEGAL_HOLD'],
    ['GW_LEGAL_HOLD', 'ANONYMISE', 'no hold'],
    ['GW_LEGAL_HOLD', 'GW_HOLD_HALT', 'hold exists'],
    ['GW_HOLD_HALT', 'ANONYMISE', 'partial OK'],
    ['GW_HOLD_HALT', 'NOTIFY_HOLD', 'full hold'],
    ['NOTIFY_HOLD', 'END_HOLD'],
    ['ANONYMISE', 'HARD_DELETE'], ['HARD_DELETE', 'CONFIRM_ERASURE'],
    ['CONFIRM_ERASURE', 'AUDIT_GDPR'], ['AUDIT_GDPR', 'END_ERASURE'],
    ['BND_30D', 'CONFIRM_ERASURE', 'deadline breach'],
  ],
  messages: [
    { from: 'POOL_MEMBER', to: 'START_GDPR', label: 'GDPR request submission' },
    { from: 'ZIP_SEND', to: 'POOL_MEMBER', label: 'Export ZIP download link' },
    { from: 'CONFIRM_ERASURE', to: 'POOL_MEMBER', label: 'Erasure confirmation' },
    { from: 'NOTIFY_HOLD', to: 'POOL_MEMBER', label: 'Legal-hold notification' },
    { from: 'ARCHIVE_COLD', to: 'POOL_ARCHIVE', label: 'Stale record batch' },
  ],
  data: [
    { id: 'DS_LIVE', kind: 'dataStore', label: 'Live DB', attached: 'IDENTIFY_STALE' },
    { id: 'DO_ZIP', kind: 'dataObject', label: 'member-data.zip', attached: 'ZIP_SEND' },
    { id: 'DS_AUDIT', kind: 'dataStore', label: 'Audit log', attached: 'AUDIT_GDPR' },
  ],
  annotations: [
    { attached: 'BND_30D', text: 'GDPR Art. 12 — respond within 30 days' },
    { attached: 'ANONYMISE', text: 'Marketplace tx records anonymised, not deleted' },
  ],
};

const P6 = {
  id: 'p6-incident', num: 6,
  title: 'Security Incident Response',
  goal: 'Detect, triage, contain, eradicate and recover from security incidents (brute-force login, leaked JWT secret, abnormal admin activity), with GDPR breach notification where personal data is exposed.',
  trigger: 'Signal start event from Monitoring / SIEM (login spike, audit anomaly, or secret-leak alert).',
  constructs: 'Signal start event, three-way exclusive gateway (severity), parallel gateway (containment split/join), intermediate catch timer (72h breach deadline), boundary timer (escalation), send/service/manual/script tasks, message flows to Users & Regulator pools, post-incident gateway, data stores & object.',
  pools: [
    { id: 'POOL_OPS', name: 'ModellingClub Operations', lanes: ['Monitoring & SIEM', 'Security On-Call', 'System', 'DPO & Legal'] },
    { id: 'POOL_USERS', name: 'Affected Users', lanes: [], blackbox: true },
    { id: 'POOL_REG', name: 'Supervisory Authority / Regulator', lanes: [], blackbox: true },
  ],
  nodes: [
    { id: 'START_SIGNAL', kind: 'startEvent', marker: 'signal', pool: 'POOL_OPS', lane: 'Monitoring & SIEM', label: 'SIEM alert received' },
    { id: 'ENRICH_TRIAGE', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'Monitoring & SIEM', label: 'Enrich alert: correlate logs, IPs, accounts' },
    { id: 'GW_SEVERITY', kind: 'exclusiveGateway', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'Severity level?' },
    { id: 'LOG_LOW', kind: 'task', sub: 'script', pool: 'POOL_OPS', lane: 'Monitoring & SIEM', label: 'Log event; raise threshold' },
    { id: 'END_LOW', kind: 'endEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Monitoring & SIEM', label: 'Closed — low severity' },
    { id: 'ASSESS_HIGH', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'Assess scope & data-exposure risk' },
    { id: 'BND_ESCALATE', kind: 'boundaryEvent', marker: 'timer', interrupting: false, attachedTo: 'ASSESS_HIGH', pool: 'POOL_OPS', lane: 'Security On-Call', label: '1h escalation' },
    { id: 'APPLY_MIT', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'System', label: 'Apply mitigations (block IPs, revoke sessions)' },
    { id: 'NOTIFY_TEAM', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'Notify team & management' },
    { id: 'END_HIGH', kind: 'endEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'High incident closed' },
    { id: 'PAR_CONTAIN', kind: 'parallelGateway', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'Begin containment' },
    { id: 'ROTATE_JWT', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'System', label: 'Rotate JWT secret (forces re-login)' },
    { id: 'BLOCK_IPS', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'System', label: 'Block IPs / rate-limit /auth/login' },
    { id: 'MAINT_MODE', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'System', label: 'Optionally engage maintenance mode' },
    { id: 'PAR_CONTAIN_JOIN', kind: 'parallelGateway', pool: 'POOL_OPS', lane: 'System', label: 'Containment complete' },
    { id: 'GW_BREACH', kind: 'exclusiveGateway', pool: 'POOL_OPS', lane: 'DPO & Legal', label: 'Personal data exposed?' },
    { id: 'NOTIFY_DPO', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'DPO & Legal', label: 'Notify DPO; start breach assessment' },
    { id: 'NOTIFY_USERS', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'Notify affected users (re-login)' },
    { id: 'TIMER_72H', kind: 'intermediateCatch', marker: 'timer', pool: 'POOL_OPS', lane: 'DPO & Legal', label: '72h GDPR deadline' },
    { id: 'NOTIFY_REG', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'DPO & Legal', label: 'Submit breach notification' },
    { id: 'ERADICATE', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'System', label: 'Eradicate threat; harden config' },
    { id: 'VERIFY_RECOVERY', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'Verify recovery; monitor recurrence' },
    { id: 'POST_MORTEM', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'Post-incident review' },
    { id: 'GW_HARDEN', kind: 'exclusiveGateway', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'Hardening task needed?' },
    { id: 'CREATE_TASK', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'Create follow-up hardening task' },
    { id: 'END_CRITICAL', kind: 'endEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Security On-Call', label: 'Incident closed' },
  ],
  flows: [
    ['START_SIGNAL', 'ENRICH_TRIAGE'], ['ENRICH_TRIAGE', 'GW_SEVERITY'],
    ['GW_SEVERITY', 'LOG_LOW', 'low'],
    ['GW_SEVERITY', 'ASSESS_HIGH', 'high'],
    ['GW_SEVERITY', 'PAR_CONTAIN', 'critical'],
    ['LOG_LOW', 'END_LOW'],
    ['ASSESS_HIGH', 'APPLY_MIT'], ['APPLY_MIT', 'NOTIFY_TEAM'], ['NOTIFY_TEAM', 'END_HIGH'],
    ['BND_ESCALATE', 'PAR_CONTAIN', 'escalate'],
    ['PAR_CONTAIN', 'ROTATE_JWT'], ['PAR_CONTAIN', 'BLOCK_IPS'], ['PAR_CONTAIN', 'MAINT_MODE'],
    ['ROTATE_JWT', 'PAR_CONTAIN_JOIN'], ['BLOCK_IPS', 'PAR_CONTAIN_JOIN'], ['MAINT_MODE', 'PAR_CONTAIN_JOIN'],
    ['PAR_CONTAIN_JOIN', 'GW_BREACH'],
    ['GW_BREACH', 'NOTIFY_DPO', 'yes'],
    ['GW_BREACH', 'ERADICATE', 'no'],
    ['NOTIFY_DPO', 'NOTIFY_USERS'], ['NOTIFY_USERS', 'TIMER_72H'],
    ['TIMER_72H', 'NOTIFY_REG'], ['NOTIFY_REG', 'ERADICATE'],
    ['ERADICATE', 'VERIFY_RECOVERY'], ['VERIFY_RECOVERY', 'POST_MORTEM'],
    ['POST_MORTEM', 'GW_HARDEN'],
    ['GW_HARDEN', 'CREATE_TASK', 'yes'],
    ['GW_HARDEN', 'END_CRITICAL', 'no'],
    ['CREATE_TASK', 'END_CRITICAL'],
  ],
  messages: [
    { from: 'NOTIFY_USERS', to: 'POOL_USERS', label: 'Incident alert & re-login notice' },
    { from: 'NOTIFY_REG', to: 'POOL_REG', label: 'GDPR Art. 33 breach notification' },
  ],
  data: [
    { id: 'DS_AUDIT', kind: 'dataStore', label: 'Audit log', attached: 'ENRICH_TRIAGE' },
    { id: 'DO_BREACH', kind: 'dataObject', label: 'Breach assessment', attached: 'NOTIFY_DPO' },
  ],
  annotations: [
    { attached: 'ROTATE_JWT', text: 'HS256 rotation invalidates all 24h tokens' },
    { attached: 'BND_ESCALATE', text: 'No on-call response in 1h → escalate to critical' },
  ],
};

const P7 = {
  id: 'p7-onboarding', num: 7,
  title: 'Member Onboarding & Hosting-Provider Provisioning',
  goal: 'Formalise a new member\'s entry into ModellingClub while the Operations committee negotiates and activates the hosting / SLA contract with a cloud provider — a three-party collaboration.',
  trigger: 'A prospective member submits the registration form; in parallel the committee starts a hosting capacity review.',
  constructs: 'Collaboration with three pools, single-lane & multi-lane pools, message start event, send/receive & user/manual/service tasks, intermediate catch message events, boundary timer event, exclusive gateways, message flows crossing pools, data object & data store.',
  pools: [
    { id: 'POOL_PM', name: 'Prospective Member', lanes: [] },
    { id: 'POOL_OPS', name: 'ModellingClub Operations', lanes: ['Membership Admin', 'Operations Committee'] },
    { id: 'POOL_CP', name: 'Cloud Provider', lanes: [] },
  ],
  nodes: [
    // Prospective Member (single lane)
    { id: 'PM_START', kind: 'startEvent', marker: 'none', pool: 'POOL_PM', lane: null, label: 'Submit registration form' },
    { id: 'PM_AWAIT_EMAIL', kind: 'intermediateCatch', marker: 'message', pool: 'POOL_PM', lane: null, label: 'Await verification email' },
    { id: 'PM_VERIFY_LINK', kind: 'task', sub: 'user', pool: 'POOL_PM', lane: null, label: 'Click verification link' },
    { id: 'PM_FIRST_LOGIN', kind: 'task', sub: 'user', pool: 'POOL_PM', lane: null, label: 'Complete first login' },
    { id: 'PM_END', kind: 'endEvent', marker: 'none', pool: 'POOL_PM', lane: null, label: 'Member active' },
    // Membership Admin lane
    { id: 'MA_START', kind: 'startEvent', marker: 'message', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Registration received' },
    { id: 'MA_CREATE', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Create pending account' },
    { id: 'MA_SEND_VERIFY', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Send verification email' },
    { id: 'MA_TIMER', kind: 'boundaryEvent', marker: 'timer', attachedTo: 'MA_AWAIT_VERIFY', pool: 'POOL_OPS', lane: 'Membership Admin', label: '24h no verification' },
    { id: 'MA_RESEND', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Resend verification email' },
    { id: 'MA_AWAIT_VERIFY', kind: 'intermediateCatch', marker: 'message', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Await verification' },
    { id: 'MA_GW_VERIFIED', kind: 'exclusiveGateway', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Email verified?' },
    { id: 'MA_EXPIRE_END', kind: 'endEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Registration expired' },
    { id: 'MA_APPROVE_BUILD', kind: 'task', sub: 'user', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Approve first build submission' },
    { id: 'MA_NOTIFY_OK', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Notify member: build approved' },
    { id: 'MA_END', kind: 'endEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Onboarding complete' },
    // Operations Committee lane
    { id: 'OC_START', kind: 'startEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Capacity review initiated' },
    { id: 'OC_REQ_QUOTE', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Send hosting quote request' },
    { id: 'OC_AWAIT_QUOTE', kind: 'intermediateCatch', marker: 'message', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Await provider quote' },
    { id: 'OC_REVIEW_SLA', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Review SLA terms & pricing' },
    { id: 'OC_GW_SLA', kind: 'exclusiveGateway', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'SLA acceptable?' },
    { id: 'OC_REJECT_END', kind: 'endEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Negotiation abandoned' },
    { id: 'OC_SIGN', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Sign hosting contract' },
    { id: 'OC_SEND_SIGNED', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Transmit signed contract' },
    { id: 'OC_AWAIT_PROV', kind: 'intermediateCatch', marker: 'message', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Await environment ready' },
    { id: 'OC_GO_LIVE', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Configure DNS & go live' },
    { id: 'OC_END', kind: 'endEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Hosting active' },
    // Cloud Provider (single lane)
    { id: 'CP_START', kind: 'startEvent', marker: 'message', pool: 'POOL_CP', lane: null, label: 'Quote request received' },
    { id: 'CP_SEND_QUOTE', kind: 'task', sub: 'send', pool: 'POOL_CP', lane: null, label: 'Issue quote & SLA' },
    { id: 'CP_RECV_CONTRACT', kind: 'intermediateCatch', marker: 'message', pool: 'POOL_CP', lane: null, label: 'Signed contract received' },
    { id: 'CP_PROVISION', kind: 'task', sub: 'service', pool: 'POOL_CP', lane: null, label: 'Provision cloud environment' },
    { id: 'CP_SEND_READY', kind: 'task', sub: 'send', pool: 'POOL_CP', lane: null, label: 'Send environment-ready notice' },
    { id: 'CP_END', kind: 'endEvent', marker: 'none', pool: 'POOL_CP', lane: null, label: 'Contract active' },
  ],
  flows: [
    ['PM_START', 'PM_AWAIT_EMAIL'], ['PM_AWAIT_EMAIL', 'PM_VERIFY_LINK'],
    ['PM_VERIFY_LINK', 'PM_FIRST_LOGIN'], ['PM_FIRST_LOGIN', 'PM_END'],
    ['MA_START', 'MA_CREATE'], ['MA_CREATE', 'MA_SEND_VERIFY'], ['MA_SEND_VERIFY', 'MA_AWAIT_VERIFY'],
    ['MA_TIMER', 'MA_RESEND'], ['MA_RESEND', 'MA_AWAIT_VERIFY'],
    ['MA_AWAIT_VERIFY', 'MA_GW_VERIFIED'],
    ['MA_GW_VERIFIED', 'MA_APPROVE_BUILD', 'verified'],
    ['MA_GW_VERIFIED', 'MA_EXPIRE_END', 'not verified'],
    ['MA_APPROVE_BUILD', 'MA_NOTIFY_OK'], ['MA_NOTIFY_OK', 'MA_END'],
    ['OC_START', 'OC_REQ_QUOTE'], ['OC_REQ_QUOTE', 'OC_AWAIT_QUOTE'],
    ['OC_AWAIT_QUOTE', 'OC_REVIEW_SLA'], ['OC_REVIEW_SLA', 'OC_GW_SLA'],
    ['OC_GW_SLA', 'OC_SIGN', 'accept'],
    ['OC_GW_SLA', 'OC_REJECT_END', 'reject'],
    ['OC_SIGN', 'OC_SEND_SIGNED'], ['OC_SEND_SIGNED', 'OC_AWAIT_PROV'],
    ['OC_AWAIT_PROV', 'OC_GO_LIVE'], ['OC_GO_LIVE', 'OC_END'],
    ['CP_START', 'CP_SEND_QUOTE'], ['CP_SEND_QUOTE', 'CP_RECV_CONTRACT'],
    ['CP_RECV_CONTRACT', 'CP_PROVISION'], ['CP_PROVISION', 'CP_SEND_READY'], ['CP_SEND_READY', 'CP_END'],
  ],
  messages: [
    { from: 'PM_START', to: 'MA_START', label: 'Registration form data' },
    { from: 'MA_SEND_VERIFY', to: 'PM_AWAIT_EMAIL', label: 'Verification email' },
    { from: 'PM_VERIFY_LINK', to: 'MA_AWAIT_VERIFY', label: 'Token confirmed' },
    { from: 'MA_NOTIFY_OK', to: 'PM_FIRST_LOGIN', label: 'Build approved' },
    { from: 'OC_REQ_QUOTE', to: 'CP_START', label: 'Quote request' },
    { from: 'CP_SEND_QUOTE', to: 'OC_AWAIT_QUOTE', label: 'Quote & SLA' },
    { from: 'OC_SEND_SIGNED', to: 'CP_RECV_CONTRACT', label: 'Signed contract' },
    { from: 'CP_SEND_READY', to: 'OC_AWAIT_PROV', label: 'Environment ready' },
  ],
  data: [
    { id: 'DS_PENDING', kind: 'dataStore', label: 'Pending accounts DB', attached: 'MA_CREATE' },
    { id: 'DO_CONTRACT', kind: 'dataObject', label: 'Signed contract PDF', attached: 'OC_SIGN' },
  ],
  annotations: [
    { attached: 'MA_TIMER', text: 'No verification in 24h → one resend' },
    { attached: 'OC_GW_SLA', text: 'Reject if cost > budget or uptime < 99.5%' },
  ],
};

const P8 = {
  id: 'p8-eol', num: 8,
  title: 'System Decommissioning / End-of-Life (EOL)',
  goal: 'Retire ModellingClub in a legally compliant, member-respectful way: announce shutdown, run a data-export window, archive retained data, revoke credentials and formally terminate the hosting contract before infrastructure teardown.',
  trigger: 'None start event: the Operations committee passes a formal EOL resolution.',
  constructs: 'Multi-pool collaboration, terminate end event, two intermediate catch timers (notice & export windows), exclusive gateway (data to preserve?), parallel lanes, send/service/manual tasks, message flows to Members & Cloud Provider, data stores & object.',
  pools: [
    { id: 'POOL_OPS', name: 'ModellingClub Operations', lanes: ['Operations Committee', 'Membership Admin', 'Legal & DPO'] },
    { id: 'POOL_MEM', name: 'Members', lanes: [] },
    { id: 'POOL_CP', name: 'Cloud Provider', lanes: [] },
  ],
  nodes: [
    // Operations Committee
    { id: 'OC_START', kind: 'startEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'EOL resolution passed' },
    { id: 'OC_ANNOUNCE', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Send shutdown announcement' },
    { id: 'OC_NOTICE_TIMER', kind: 'intermediateCatch', marker: 'timer', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Wait 30-day notice period' },
    { id: 'OC_ENABLE_EXPORT', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Enable final data-export window' },
    { id: 'OC_EXPORT_TIMER', kind: 'intermediateCatch', marker: 'timer', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Wait 30-day export window' },
    { id: 'OC_DISABLE_EXPORT', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Disable export & lock platform' },
    { id: 'OC_GW_PRESERVE', kind: 'exclusiveGateway', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Data to preserve?' },
    { id: 'OC_MIGRATE', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Export / hand over preserved data' },
    { id: 'OC_ARCHIVE', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Write full archive to cold storage' },
    { id: 'OC_REVOKE', kind: 'task', sub: 'service', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Revoke keys, tokens & credentials' },
    { id: 'OC_TERMINATE', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Send contract termination notice' },
    { id: 'OC_AWAIT_TEARDOWN', kind: 'intermediateCatch', marker: 'message', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Await teardown confirmation' },
    { id: 'OC_FINAL_NOTICE', kind: 'task', sub: 'send', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'Publish final shutdown notice' },
    { id: 'OC_END', kind: 'endEvent', marker: 'terminate', pool: 'POOL_OPS', lane: 'Operations Committee', label: 'System fully decommissioned' },
    // Legal & DPO
    { id: 'DPO_START', kind: 'startEvent', marker: 'message', pool: 'POOL_OPS', lane: 'Legal & DPO', label: 'EOL signal received' },
    { id: 'DPO_REVIEW', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Legal & DPO', label: 'Review data-retention obligations' },
    { id: 'DPO_RETENTION', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Legal & DPO', label: 'Segregate records for legal retention' },
    { id: 'DPO_ARCHIVE', kind: 'task', sub: 'manual', pool: 'POOL_OPS', lane: 'Legal & DPO', label: 'Transfer legal records to long-term archive' },
    { id: 'DPO_END', kind: 'endEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Legal & DPO', label: 'Legal records secured' },
    // Membership Admin
    { id: 'MA_EXPORT_WINDOW', kind: 'startEvent', marker: 'message', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Export-window open signal' },
    { id: 'MA_MONITOR', kind: 'task', sub: 'user', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Monitor export requests; support members' },
    { id: 'MA_END', kind: 'endEvent', marker: 'none', pool: 'POOL_OPS', lane: 'Membership Admin', label: 'Member support closed' },
    // Members
    { id: 'MEM_ANNOUNCE', kind: 'startEvent', marker: 'message', pool: 'POOL_MEM', lane: null, label: 'Receive shutdown announcement' },
    { id: 'MEM_DOWNLOAD', kind: 'task', sub: 'user', pool: 'POOL_MEM', lane: null, label: 'Download personal data export' },
    { id: 'MEM_FINAL', kind: 'intermediateCatch', marker: 'message', pool: 'POOL_MEM', lane: null, label: 'Receive final shutdown notice' },
    { id: 'MEM_END', kind: 'endEvent', marker: 'none', pool: 'POOL_MEM', lane: null, label: 'Data retained locally' },
    // Cloud Provider
    { id: 'CP_TERMINATION', kind: 'startEvent', marker: 'message', pool: 'POOL_CP', lane: null, label: 'Termination notice received' },
    { id: 'CP_TEARDOWN', kind: 'task', sub: 'service', pool: 'POOL_CP', lane: null, label: 'Tear down VPS, storage & DNS' },
    { id: 'CP_CONFIRM', kind: 'task', sub: 'send', pool: 'POOL_CP', lane: null, label: 'Send teardown confirmation' },
    { id: 'CP_END', kind: 'endEvent', marker: 'none', pool: 'POOL_CP', lane: null, label: 'Contract closed' },
  ],
  flows: [
    ['OC_START', 'OC_ANNOUNCE'], ['OC_ANNOUNCE', 'OC_NOTICE_TIMER'],
    ['OC_NOTICE_TIMER', 'OC_ENABLE_EXPORT'], ['OC_ENABLE_EXPORT', 'OC_EXPORT_TIMER'],
    ['OC_EXPORT_TIMER', 'OC_DISABLE_EXPORT'], ['OC_DISABLE_EXPORT', 'OC_GW_PRESERVE'],
    ['OC_GW_PRESERVE', 'OC_MIGRATE', 'yes — preserve'],
    ['OC_GW_PRESERVE', 'OC_ARCHIVE', 'no — archive only'],
    ['OC_MIGRATE', 'OC_ARCHIVE'], ['OC_ARCHIVE', 'OC_REVOKE'], ['OC_REVOKE', 'OC_TERMINATE'],
    ['OC_TERMINATE', 'OC_AWAIT_TEARDOWN'], ['OC_AWAIT_TEARDOWN', 'OC_FINAL_NOTICE'],
    ['OC_FINAL_NOTICE', 'OC_END'],
    ['DPO_START', 'DPO_REVIEW'], ['DPO_REVIEW', 'DPO_RETENTION'],
    ['DPO_RETENTION', 'DPO_ARCHIVE'], ['DPO_ARCHIVE', 'DPO_END'],
    ['MA_EXPORT_WINDOW', 'MA_MONITOR'], ['MA_MONITOR', 'MA_END'],
    ['MEM_ANNOUNCE', 'MEM_DOWNLOAD'], ['MEM_DOWNLOAD', 'MEM_FINAL'], ['MEM_FINAL', 'MEM_END'],
    ['CP_TERMINATION', 'CP_TEARDOWN'], ['CP_TEARDOWN', 'CP_CONFIRM'], ['CP_CONFIRM', 'CP_END'],
  ],
  messages: [
    { from: 'OC_ANNOUNCE', to: 'MEM_ANNOUNCE', label: 'Shutdown announcement' },
    { from: 'OC_START', to: 'DPO_START', label: 'EOL resolution signal' },
    { from: 'OC_ENABLE_EXPORT', to: 'MA_EXPORT_WINDOW', label: 'Export window open' },
    { from: 'OC_ENABLE_EXPORT', to: 'MEM_DOWNLOAD', label: 'Export window open' },
    { from: 'OC_FINAL_NOTICE', to: 'MEM_FINAL', label: 'Final shutdown notice' },
    { from: 'OC_TERMINATE', to: 'CP_TERMINATION', label: 'Contract termination notice' },
    { from: 'CP_CONFIRM', to: 'OC_AWAIT_TEARDOWN', label: 'Teardown confirmation' },
  ],
  data: [
    { id: 'DS_COLD', kind: 'dataStore', label: 'Cold storage archive', attached: 'OC_ARCHIVE' },
    { id: 'DS_LEGAL', kind: 'dataStore', label: 'Legal retention repository', attached: 'DPO_ARCHIVE' },
    { id: 'DO_EXPORT', kind: 'dataObject', label: 'Member data ZIP', attached: 'MEM_DOWNLOAD' },
  ],
  annotations: [
    { attached: 'OC_NOTICE_TIMER', text: '30-day statutory notice period' },
    { attached: 'DPO_RETENTION', text: 'Financial / contest records kept per law (~7y)' },
  ],
};

module.exports = [P1, P2, P3, P4, P5, P6, P7, P8];
